# Generated by Django 5.0.6 on 2024-06-14 09:26

import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True)),
                ('is_private', models.BooleanField(default=False)),
                ('memebers', models.ManyToManyField(blank=True, related_name='video_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
