# Generated by Django 5.0.6 on 2024-06-14 16:48

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_room',
            name='name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
