# Generated by Django 5.0.6 on 2024-07-03 14:51

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochat', '0008_alter_video_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_room',
            name='name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
