# Generated by Django 5.0.6 on 2024-07-10 17:22

import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochat', '0011_alter_video_room_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_room',
            name='name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='Video_text_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Video_text_room', max_length=20)),
                ('is_random', models.BooleanField(default=True)),
                ('memebers', models.ManyToManyField(blank=True, related_name='video_text_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
